### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'kivy'

### ISSUE THREAD

**Issue by Radobilly** [kivy-garden/garden#23]
When executing garden search  from commandline in Ubuntu 16.04 using python 2.7.
Seems to exists in both 1.9.0 from the ubuntu repository and 1.9.1 from the kivy site
http://pastebin.com/7R9MVwcF

`jan@tobis:~/projects/kivylayouts$ garden search graph`
`[WARNING] [Config      ] Older configuration version detected (13 instead of 14)`
`[WARNING] [Config      ] Upgrading configuration in progress.`
`[INFO   ] [Logger      ] Record log in /home/jan/.kivy/logs/kivy_16-07-27_20.txt`
`[INFO   ] [Kivy        ] v1.9.1`
`[INFO   ] [Python      ] v2.7.11+ (default, Apr 17 2016, 14:00:29)`
`[GCC 5.3.1 20160413]`
`graph - Displays plots on a graph.`
`Traceback (most recent call last):`
`File "/usr/local/bin/garden", line 223, in <module>`
`GardenTool().main(sys.argv[1:])`
`File "/usr/local/bin/garden", line 90, in main`
`if self.options.kivy and garden_kivy_dir is None:`
`AttributeError: 'Namespace' object has no attribute 'kivy'`

**Comment by matham** [comment]
Try with garden master. I think it may have been fixed there.

**Comment by Radobilly** [comment]
Thanks. seems to work :)

**Comment by jb1123** [comment]
I have similar error, what is 'garden master'?

**Comment by devMoxie** [comment]
@jb1123 uninstall Kivy-Garden, then:
pip install git+https://github.com/kivy-garden/garden@master

**Comment by KeyWeeUsr** [comment]
Fixed in master.

**Comment by jfinkhaeuser** [comment]
With master:
```
options.package = [p.lower() for p in options.package]
 AttributeError: 'Namespace' object has no attribute 'package'
```

**Comment by Rob-bb** [comment]
Hi, still a problem, using garden master works, but it is now 2019.  Does this mean the kivy garden is a dead end?

**Comment by poikilos** [comment]
Even installing master has the error now.
